### ISSUE TITLE
Custom Steering Functions & Meaning of torch.mean

### ISSUE THREAD

**Issue by nickmitchko** [Mihaiii/llm_steer#5]
What shape must the delta resulting from a custom steering function be?

I see in [llm_steer#107](https://github.com/Mihaiii/llm_steer/blob/main/llm_steer.py#L107) that the new forward function takes the mean of the steering vector and adds that to the tokens passed in. This makes sense but intuitively adds the same direction to that entire layer.

```py
#LN107 Mean of steering vector
delta = torch.mean(
    elem.coeff * elem.tensor[:, elem.try_keep_nr :, :],
    dim=1,
    keepdim=True,
)
#LN117 Adding in the steering "difference"
kwargds["hidden_states"][:, elem.try_keep_nr :, :] += delta
```

Wouldn't it make more sense if the activation of a steering vector happens across the entire matrix, something like this?

```py
delta = elem.coeff * elem.tensor[:, elem.try_keep_nr :, :] # (entire matrix of that token)
#LN117 Adding in the steering "difference"
kwargds["hidden_states"][:, elem.try_keep_nr :, :] += delta
```

**Comment by Mihaiii** [comment]
Hey!

You can see [here](https://github.com/Mihaiii/llm_steer/pull/2#issue-2241677364) an example of a custom steering function .

Regarding your actual question, if I recall correctly, I decided to use broadcasting in order to avoid tensor mismatch errors on `kwargds["hidden_states"][:, elem.try_keep_nr :, :] += delta` when doing the sum.

The actual tensor size depends on whether the sampling is done with `use_cache=True` or `use_cache=False` and doing the mean ensures it will work in all cases.

If the follow up question is "why mean and not some other operation?", then the answer is ¯\_(ツ)_/¯. This one seems to work the best. Please keep in mind that this library is primarily for experimenting :) . It's not guaranteed that the default function provides the best results.

Let me know if you have other questions.

**Comment by nickmitchko** [comment]
Thanks for the explanation, I think the best results might come from when the tensor activation comes element wise and not mean averaged. I'll experiment and play around and let you know if there's a generic solution. 

For context, I am experimenting on self-optimizing steering vectors, [here](https://github.com/nickmitchko/llm_steer-oobabooga/).
